/**
 * Imports
 *
 * Import the state and utilities protocol buffer
 * files generated by protoc on application start
 *
 * This requires the state.proto and utilities.proto
 * to be present in src/ipc/. The location will probably
 * change once we bring in the simulator. Update
 * package.json with the build instructions accordingly.
 */
var PBUtilities = require("./utilities_pb.js");
var PBState     = require("./state_pb.js");

module.exports = {
    /**
     * Executes the start script/command and reads from stdout of the child process
     * @param startCommand specifies the start script/command
     */
    startSimulator : function (startCommand) {
        var childProcess = require('child_process');
        var simulatorProcess = childProcess.exec(startCommand, function (error, stdout, stderr) {
            if(error){
                console.log(error.stack);
                console.log('Error code: '+error.code);
                console.log('Signal received: '+error.signal);
            }
            console.log(stdout);
            // Call Protocol Buffer logic here
        });
        simulatorProcess.on('exit', function (code) {
            console.log('Child process exited with exit code '+code); 
        });
    }
}
